Add support for offline updates of Romi webservice
wpilibsuite/WPILibPi pull request #169
Opened 2020-12-07 19:21 UTC by zhiquanyeo

2020-12-09 08:11 UTC, PeterJohnson requested changes

2020-12-09 08:11 UTC, PeterJohnson commented on deps/tools/configServer/Makefile
> +        '-DNODE_HOME="${NODE_HOME}"' \
Indentation seems a little off here?

2020-12-09 08:11 UTC, PeterJohnson commented on deps/tools/configServer/Makefile
> +NODE_HOME?=/home/${FIRST_USER_NAME}/.nvm/versions/node/v14.15.0/bin
FIRST_USER_NAME won’t work here, that’s not set on the pi itself, just during the build.  I think we can just make it /home/pi or ${HOME}.

2020-12-09 08:11 UTC, PeterJohnson commented on deps/tools/configServer/src/RomiStatus.cpp
> +
Don’t need an additional newline here

2020-12-09 08:11 UTC, PeterJohnson commented on deps/tools/configServer/src/WebSocketHandlers.cpp
> +      auto installSuccess = [&](wpi::WebSocket& s) {
I think you need to capture with = here (by value), instead of with & (by reference), as statusfunc is a local variable.  Ditto for installFailure.

2020-12-09 12:08 UTC, zhiquanyeo commented on deps/tools/configServer/Makefile
> +NODE_HOME?=/home/${FIRST_USER_NAME}/.nvm/versions/node/v14.15.0/bin
It seemed to work though, and `EXEC_HOME` has it set to /home/${FIRST_USER_NAME}` as well. I can change both of them to be `${HOME}` instead

2020-12-09 12:10 UTC, zhiquanyeo commented on deps/tools/configServer/Makefile
> +NODE_HOME?=/home/${FIRST_USER_NAME}/.nvm/versions/node/v14.15.0/bin
I'm guessing it worked during the image generation process since `FIRST_USER_NAME` was set at that time

2020-12-09 18:38 UTC, AustinShalit commented
/azp run

2020-12-10 06:00 UTC, PeterJohnson approved these changes

2020-12-10 12:44 UTC, merged